/*
 * DuplicatedDataException.h
 *
 *  Created on: 08/06/2021
 *      Author: Tiago Oliveira
 */

#ifndef HEADERS_EXCEPTIONS_DUPLICATEDDATAEXCEPTION_H_
#define HEADERS_EXCEPTIONS_DUPLICATEDDATAEXCEPTION_H_





#endif /* HEADERS_EXCEPTIONS_DUPLICATEDDATAEXCEPTION_H_ */
